### ISSUE TITLE
No star is ur bot working 

### ISSUE THREAD

**Issue by DONpromise1738-dot** [FakerPK/NodePayBot#1]

**Comment by FakerPK** [comment]
Unfortunately after the recent update to the NodePay ecosystem, they have removed the support for ISP and data center proxies which are mainly what my script was made for, I’ll work on a revised script that supports residential proxies, but for now this script is unusable, I’m really sorry :(

**Comment by DONpromise1738-dot** [comment]
Ok let us know when an update is out
